module TestLinearTransport
using MPI
using BcubeGmsh
using MPIUtils
using WriteVTK
using LinearAlgebra
include(joinpath(@__DIR__, "run.jl"))

function run()
    outdir = joinpath(@__DIR__, "tmp")

    # Init MPI
    MPI.Initialized() || MPI.Init()
    comm = MPI.COMM_WORLD
    np = MPI.Comm_size(comm)

    # Then generate the mesh of a rectangle using Gmsh and read it
    tmp_path = joinpath(outdir, "tmp.msh")
    @only_root println("building mesh...")
    nx = 51
    ny = nz = 2
    lx = ly = lz = 1.0
    @only_root BcubeGmsh.gen_hexa_mesh(
        tmp_path,
        :hexa;
        nx,
        ny,
        nz,
        lx,
        ly,
        lz,
        xc = 0.0,
        yc = 0.0,
        zc = 0.0,
        n_partitions = np,
        split_files = true,
        create_ghosts = true,
        bnd_names = ("Xmin", "Xmax", "Ymin", "Ymax", "Zmin", "Zmax"),
    )
    MPI.Barrier(comm) # wait for the mesh to be generated by proc 0

    @only_root println("reading mesh...")
    dmesh = read_partitioned_msh(tmp_path, comm)

    # Init u
    u = MeshCellData(
        map(x -> norm(x) < 0.1 ? 1.0 : 0.0, Bcube.get_cell_centers(parent(dmesh))),
    )

    c_norm = 1.0
    CFL = 0.5
    dt = CFL * min(lx / (nx - 1), ly / (nz - 1), lz / (nz - 1)) / c_norm

    bcube_io = (; dmesh, data = Dict("u" => u))
    bcube_solver = setup_simulation(bcube_io, c_norm .* normalize([1.0, 0.0, 0.0]))
    BcubeMPI.write_pvtk(
        joinpath(outdir, "linear-transport"),
        0,
        0.0,
        dmesh,
        Dict("u" => (var_on_centers(bcube_solver.sol, parent(dmesh)), VTKCellData()));
        append = false,
    )

    t = 0.0
    for i in 1:100
        @only_root println("Iteration $i")
        t += dt
        step_forward(bcube_solver)

        BcubeMPI.write_pvtk(
            joinpath(outdir, "linear-transport"),
            i,
            t,
            dmesh,
            Dict("u" => (var_on_centers(bcube_solver.sol, parent(dmesh)), VTKCellData()));
            append = true,
        )
    end
end

run()
end